# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/b66fa9a2-3de1-4fd2-a1f0-3de7aa92a6f0";
      fsType = "ext4";
    };

  fileSystems."/media" =
    {
      device = "/dev/disk/by-uuid/464eda6e-effe-4950-affc-918dd1dbfe2d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D63A-DFE8";
      fsType = "vfat";
    };
  fileSystems."/srv/Satisfactory" =
    {
       fsType = "tmpfs";
       options = [ "defaults" "size=6g" "gid=1002" "uid=1002" ];
    };
  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
